### PR TITLE
Use setnx in add_or_replace() function when the $add argument is set

### PR DESCRIPTION
**Pull request by ffxluca**
Fix for #166

### CODE REVIEW

**Comment by tillkruss** [comment]
@naxvog: Any thoughts?

**Comment by ffxluca** [comment]
Let me try and put some random `sleep()` statements to actually see the `setnx` returning false

**Comment by naxvog** [comment]
Just to reiterate:
* There is a race condition between checking for existence of a key and setting the key while multiple WordPress instances (clients) trying to add a key at the same time.
* The race condition occurs if client A checked the existence of the key and has not yet set the key while client B does the same existence-check. Both clients will set the key in this case resulting in an error due to the `SETEX` command being called on a value that already exists overriding that value.
* In the example above client A should set the key, client B should receive `false` as the key already exists.

The fix seems fine to me. Nice catch!

However as far as I know both `SETEX` and `SETNX` are atomic redis operations so the comments are a bit misleading. The problem that introduces the race condition is the existence check not the command itself.

On the performance side this should perform better than the old implementation as the existence check is done by `SETNX` and the expiry is just set if it is required. So there is a minimum of 1 and a maximum of 2 redis commands sent whereas before there were always 2 being sent while adding a key.

**Comment by tillkruss** [comment]
Can we use `SET $key $value NX EX $expiration` instead of the extra `EXPIRE` call?

**Comment by naxvog** [comment]
To quote the redis documentation for the options to the `SET` command:
>\>= 2.6.12: Added the EX, PX, NX and XX options.

(Version 2.6.12 release: [2013-03-29](https://code.google.com/archive/p/redis/downloads))

**Requirements:** Currently the minimum Redis requirement seems to be 2.0.0 (released [2010-09-03](https://code.google.com/archive/p/redis/downloads?page=4)) as `SETEX` is used. However we would reduce the minimum requirement to Redis 1.0.0 using `SETNX` as proposed.

**Support:** phpredis ([doc](https://github.com/phpredis/phpredis#set)) and predis ([somewhat related issue](https://github.com/nrk/predis/issues/309#issuecomment-221203097)) are supporting these options.

**Performance:** From a performance standpoint one command should be ideal.

**Comment by tillkruss** [comment]
This is where it would be ideal to collect telemetry. I’ve never seen anything older than Redis 3, but who know.

**Comment by naxvog** [comment]
Well we could just use `version_compare` to implement this. The performance increase might be worth it. As long as we do the version compare once we should be fine.

**Comment by ffxluca** [comment]
> Just to reiterate:
> ... 
> The fix seems fine to me. Nice catch!
You got it, thanks for rephrasing it!

> However as far as I know both `SETEX` and `SETNX` are atomic redis operations so the comments are a bit misleading. The problem that introduces the race condition is the existence check not the command itself.
Yes! I can remove the inline comments then.

> On the performance side this should perform better than the old implementation as the existence check is done by `SETNX` and the expiry is just set if it is required. So there is a minimum of 1 and a maximum of 2 redis commands sent whereas before there were always 2 being sent while adding a key.

**Comment by tillkruss** [comment]
@ffxluca: Can you push the change from `EXPIRE + SETNX` to use `SET $key $value NX EX $expiration?

**Comment by tillkruss** [comment]
@naxvog: Do you want bring this home, or shall I?

**Comment by naxvog** [comment]
Will push a PR in a bit

**Pull request closed without merging**
