### PR TITLE
improved tab switching using js history api

### PR DESCRIPTION
**Pull request by naxvog**
Improved upon #234

History is now correctly set and respected on back and forward navigation or jumps.

### CODE REVIEW

**Comment by tillkruss** [comment]
Closing in favor of 7bb1f3e.

**Comment by tillkruss** [comment]
@naxvog: Do you still have some kind of jumping occur when navigating or clicking tabs?

**Comment by naxvog** [comment]
Have not tested this but I see the following issues by looking at the code:
* `e.preventDetault` should be `return false` for jQuery events. Either way this should fix the jumping issue.
* `addEventListener` should be specified via jQuery and namespaces
* History API Implementation is worthless if you only push states but don't react to those states if navigation occurs (back/forward)
* The `#top` anchor needs to exist to ensure that a link to a specific tab (from another page) will still show the top of the page and not just the tab.

**Comment by tillkruss** [comment]
>History API Implementation is worthless if you only push states but don't react to those states if navigation occurs (back/forward)

That's working with `hashchange`, thanks for pointing it out.

>The #top anchor needs to exist to ensure that a link to a specific tab (from another page) will still show the top of the page and not just the tab.

That's because of bad design. Will fix that

**Pull request closed without merging**
