### PR TITLE
Customizations for Spinup WP

### PR DESCRIPTION
**Pull request by tillkruss**
Customizations for SpinupWP.com to easily rollout the full plugin, instead of a `object-cache.php` fork.

### CODE REVIEW

**Comment by tillkruss** [comment]
@gilbitron @A5hleyRich: I can't include [this change](https://github.com/deliciousbrains/spinupwp-plugin/commit/7cc2b8c68cb3ff886431bdfe8511657f6503ac67), are you able to set `WP_REDIS_SELECTIVE_FLUSH` for deployments?

**Comment by naxvog** [comment]
I don't really see the point of supporting constants with essentially different prefixes. Supporting environment variables would be a nice addition though.

**Comment by gilbitron** [comment]
@tillkruss We're inclined to agree with @naxvog. If constants could be set using `getenv` that's all we would require. No need for SpinupWP prefixes. In our case, we'd need `getenv` support for `WP_REDIS_PREFIX` and `WP_REDIS_SELECTIVE_FLUSH`.

**Comment by tillkruss** [comment]
@gilbitron: Done👍🏻

Anything else before we push this out?

**Review by naxvog — APPROVED** [review]

**Comment by naxvog** [comment]
We should also allow all connection parameter and configuration constants to be set as environment variables.

(`getenv` using a parameter might be the wrong function to do this as it will return `false` if the specific variable is not present - an issue when dealing with boolean variables/constants)

**Comment by tillkruss** [comment]
We can add individual ones upon request, in the meantime I'd recommend this:

```php
define( 'WP_REDIS_HOST', getenv('WP_REDIS_HOST') ?: '127.0.0.1' );
define( 'WP_REDIS_PORT', getenv('WP_REDIS_TOKEN') ?: 6379 );
```

**Comment by A5hleyRich** [comment]
Awesome, thanks @tillkruss. We'll get the modifations made in SpinupWP to start distrubuting the full plugin 💪

**Pull request merged**
