### PR TITLE
Add ssl parameter for predis

### PR DESCRIPTION
**Pull request by MartinSilberFemale**
I just tested this for predis and I think it won't work for phpredis or credis.

So there needs to a bit more of adjustment.

### CODE REVIEW

**Comment by naxvog** [comment]
Hi Martin,
have you tried using the [`tls` scheme](https://github.com/rhubarbgroup/redis-cache/wiki/Connection-Parameters#wp_redis_scheme-default-tcp)?

**Comment by MartinSilberFemale** [comment]
Hi @naxvog,

this is what my code looks like: 
` $redis = (object)parse_url($_ENV['REDIS_URL']);
    define('WP_REDIS_HOST', $redis->host);
    define('WP_REDIS_PORT', $redis->port);
    define('WP_REDIS_PASSWORD', $redis->pass);
    define('WP_REDIS_SCHEME', 'tls');
    define('WP_REDIS_CLIENT', 'predis');
    define('WP_REDIS_SSL', ['verify_peer' => false, 'verify_peer_name' => false]);`

I can establish the connection, when I add the changes to make the ssl call with the paramters.

Is there already another way to pass them?

**Comment by naxvog** [comment]
Thanks for clarifying. So far only predis allows for SSL connection parameters to be passed. Currently there is no option to do so.

Credis and phpredis do not support those parameters so a new constant will have to be named `WP_REDIS_PREDIS_SSL` (or similar). For the same reason it might be better to check and add the connection parameter in the `connect_using_predis` method.

@tillkruss What is your take on this?

Reference: [Predis connection parameters](https://github.com/predis/predis/blob/f07f8d01fe0093e3fd9fc2a4573d119fcb8220a9/README.md#connecting-to-redis)

**Comment by tillkruss** [comment]
PhpRedis supports the `tls://` scheme as of v5.3.0 and it also supports custom TLS options with a similar syntax passed into the constructor.

Credis seems to support TLS as well, but I haven't looked into it.

**Comment by naxvog** [comment]
Have not found any documentation on PhpRedis' part ([only found the `tls://` scheme](https://github.com/phpredis/phpredis#pconnect-popen)) regarding SSL parameters but I have looked in the sourcecode of Credis and as far as I saw there are none.

**Comment by tillkruss** [comment]
Both describe the scheme in their readme:

https://github.com/phpredis/phpredis#connect-open

https://github.com/colinmollenhour/credis#tls-connection-string

I know PhpRedis supports socket options like Predis does. Not sure with Credis.

**Comment by tillkruss** [comment]
@MartinSilberFemale: Are you able to add support for PhpRedis as well in this PR?

**Comment by MartinSilberFemale** [comment]
@tillkruss Yeah if think I could try that, but would take some time, if this is okay for you :) (not more than 7 days)

**Comment by tillkruss** [comment]
Any update on this?

**Comment by MartinSilberFemale** [comment]
@tillkruss Sorry, that I didn't reply. 

Right now I am really busy with other projects, but I will try to take a look at it next week.

**Pull request closed without merging**
