### PR TITLE
feat: support $force in wp_cache_get_multi()

### PR DESCRIPTION
**Pull request by LucasLeandro1204**

### CODE REVIEW

**Comment by LucasLeandro1204** [comment]
should resolve #187

**Comment by LucasLeandro1204** [comment]
@tillkruss I'm not sure if it's correct, never worked with a wp package before, kinda hard to navigate through the code.

**Comment by tillkruss** [comment]
Hey @LucasLeandro1204, would you mind un-doing the whitespace changes you committed? You could even use `phpcbf` to fix it.

**Comment by LucasLeandro1204** [comment]
@tillkruss done

**Comment by tillkruss** [comment]
Thanks @LucasLeandro1204. I had a look at this and it wasn't quite doing the job.

I've solved it in 6089240 and 2777a40.

**Comment by LucasLeandro1204** [comment]
that's ok bro! I just gave it a try

**Pull request closed without merging**
