### PR TITLE
Settings page tabs

### PR DESCRIPTION
**Pull request by naxvog**
Added tab functionality and moved the Pro promotion to a dedicated sidebar.
Styling heavily inspired by Yoast SEO

### CODE REVIEW

**Comment by tillkruss** [comment]
@naxvog: Can you post a mobile and desktop screenshot?

**Comment by naxvog** [comment]
**Desktop**
desktop
**Small Screen**
small-screen
**Mobile**
mobile

**Comment by tillkruss** [comment]
Nice. Is this ready to merge?

**Comment by naxvog** [comment]
I do think so. We now have more space to put stuff™ and to be quite verbose about certain aspects.

**Pull request merged**
