### PR TITLE
Settings file generation

### PR DESCRIPTION
**Pull request by naxvog**
I am proposing a settings file located at `WP_CONTENT_DIR . '/redis_object_cache/settings.php` defining the location of the plugin (and potentially a basic configuration as per #173).

This change makes it possible to de-clutter the drop-in by splitting the cache function and class definitions into their respective files in the includes directory.

### CODE REVIEW

**Comment by tillkruss** [comment]
We'll have to rebase after #246 is merged, this before I can review it.

**Comment by naxvog** [comment]
> 
> 
> We'll have to rebase after #246 is merged, this before I can review it.

done

**Comment by tillkruss** [comment]
@naxvog: Can you revert touching the `object-cache.php` file and just stick to settings file changes?

**Comment by naxvog** [comment]
Well if I decouple the settings file generation there would not be any functionality or benefit left. The whole thing exists to allow for `WP_REDIS_PLUGIN_PATH` to be defined before any plugin is loaded an therefore load the cache functions as well as the class from the plugin directory.
How about tagging this for the next feature release 2.1?

**Comment by tillkruss** [comment]
Closing this for now. Open to pull requests.

**Pull request closed without merging**
