### PR TITLE
"Statification" of the plugin class

### PR DESCRIPTION
**Pull request by naxvog**
Transformed every method of the plugin class to a static one. Started from the bottom up and replaced all calls as needed.

Introduced getter methods for `Plugin::$screen` and `Plugin::$page` and moved the constructor logic to a new `init` method - scrapped the singleton pattern in the process.

Removed the `redis_object_cache` function as there is no more instance to retrieve.

Changes will satisfy #259 No. 4 and 7 for the plugin class.

### CODE REVIEW

**Comment by naxvog** [comment]
signed commits and rebased against [2.0.13](https://github.com/rhubarbgroup/redis-cache/tree/2.0.13)

**Comment by tillkruss** [comment]
@naxvog: This is looking pretty good on a quick glance. How are you feeling about the change?

**Comment by naxvog** [comment]
Looks good from my side. Just tested the CLI commands to be sure :wink:

**Comment by naxvog** [comment]
Rebased to `2.0.15`

**Pull request closed without merging**
