### PR TITLE
Make static analysis possible

### PR DESCRIPTION
**Pull request by szepeviktor**
@phpstan is for strict OOP code. Please understand that.

I've finished work at

>  [ERROR] Found 15 errors

From https://github.com/rhubarbgroup/redis-cache/pull/294#issuecomment-723194793

### CODE REVIEW

**Comment by szepeviktor** [comment]
### How it works

It makes a copy of `WP_Object_Cache` as `Redis_Pro_WP_Object_Cache` extending core's class.
Runs static analysis on that copy but you have to fix it in the original one.

In the 15 problems above there are false positives.

**Comment by szepeviktor** [comment]
Current output of `composer run-script analyze`

```
 ------ -------------------------------------------------------------------
  Line   includes/class-autoloader.php
 ------ -------------------------------------------------------------------
  40     Parameter #1 $autoload_function of function spl_autoload_register
         expects callable(string): void,
         array($this(Rhubarb\RedisCache\Autoloader), 'load_class') given.
 ------ -------------------------------------------------------------------

 ------ ---------------------------------------------------------------------
  Line   includes/class-plugin.php
 ------ ---------------------------------------------------------------------
  261    Parameter #3 $deps of function wp_enqueue_style expects
         array<string>, null given.
  337    Parameter #3 $deps of function wp_enqueue_script expects
         array<string>, null given.
  508    Method Rhubarb\RedisCache\Plugin::get_redis_version() should return
         string|null but return statement is missing.
  878    Access to an undefined property object::$cache.
  888    Negated boolean expression is always false.
 ------ ---------------------------------------------------------------------

 ------ ----------------------------------------------------------------------
  Line   includes/ui/diagnostics.php
 ------ ----------------------------------------------------------------------
  35     Class WP_Object_Cache constructor invoked with 1 parameter, 0
         required.
  106    Call to function is_array() with null will always evaluate to false.
  107    Result of && is always false.
  107    Result of && is always false.
  112    Result of && is always false.
 ------ ----------------------------------------------------------------------

 ------ ---------------------------------------------------------------
  Line   includes/ui/query-monitor.php
 ------ ---------------------------------------------------------------
  16     Call to protected method before_non_tabular_output() of class
         QM_Output_Html.
  133    Call to protected method after_non_tabular_output() of class
         QM_Output_Html.
 ------ ---------------------------------------------------------------

 ------ -------------------------------------
  Line   includes/ui/tabs/overview.php
 ------ -------------------------------------
  14     Variable $roc might not be defined.
 ------ -------------------------------------

 ------ ----------------------------------------------------------------------
  Line   php7-tools/object-cache.php
 ------ ----------------------------------------------------------------------
  519    Call to function is_null() with mixed will always evaluate to false.
 ------ ----------------------------------------------------------------------
```

**Comment by tillkruss** [comment]
Can we get the static analysis without the actual changes?

**Comment by szepeviktor** [comment]
You may change this PR as you wish.
I am not a user, just making PHPStan more popular :)

**Comment by szepeviktor** [comment]
This is a technology example, not a PR.

**Comment by szepeviktor** [comment]
A simple command may suffice: `git checkout develop -- includes/`

**Comment by szepeviktor** [comment]
All right: I delete myself :)

**Comment by tillkruss** [comment]
@szepeviktor should we bring this home, or close it?

**Comment by szepeviktor** [comment]
@tillkruss Static analysis has great benefits.
What should I modify in this PR?

**Comment by tillkruss** [comment]
@szepeviktor If this is ready to be merged on your end, maybe can we change `php7-tools` to `php-tools`, since it will age poorly?

**Comment by szepeviktor** [comment]
@tillkruss Done 🍏

**Comment by tillkruss** [comment]
@szepeviktor Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
