### PR TITLE
Really fix all EC problems

### PR DESCRIPTION
**Pull request by szepeviktor**
@tillkruss #390 was half-done and ❌failing.

### CODE REVIEW

**Comment by tillkruss** [comment]
The `readme.txt` changes won't work like that.

**Comment by szepeviktor** [comment]
Yes. Wrong `sed` command!

**Comment by szepeviktor** [comment]
@tillkruss I'd like to with those few PHPStan ignores...

**Comment by szepeviktor** [comment]
Now everything should be 🍏

**Comment by szepeviktor** [comment]
Very strange! On my server "Ignored error pattern ... was not matched"
In CI it is all green!

**Comment by szepeviktor** [comment]
> Very strange! On my server "Ignored error pattern ... was not matched",
> in CI it is all green!

Got it! The cause is the latest release of PHPStan: v1.8.3

**Pull request merged**
