### PR TITLE
isset() does not allow null

### PR DESCRIPTION
**Pull request by szepeviktor**
Please see https://www.php.net/manual/en/function.isset.php

### CODE REVIEW

**Comment by tillkruss** [comment]
Why do you want to remove the check? The password might be `null`.

**Comment by szepeviktor** [comment]
> The password might be `null`.

@tillkruss The password is `null` `if ( isset( $parameters['password'] ) ) {` will not run
as _isset() does not allow null_

**Comment by tillkruss** [comment]
Gotcha, the code made no sense. @naxvog approved?

**Comment by szepeviktor** [comment]
@phpstan taught me that `isset` work this way.

**Comment by szepeviktor** [comment]
# ✔️

**Pull request merged**
