### PR TITLE
Do not display the dropin message if WP_REDIS_DISABLE_DROPIN_BANNERS …

### PR DESCRIPTION
**Pull request by leopoiroux**
…exists and true.

I would like to control when I can replace object-cache.php. As long as WP_REDIS_DISABLE_DROPIN_BANNERS, I want to be sure that no user of my site can overwrite object-cache.php (we are several admin)

### CODE REVIEW

**Comment by leopoiroux** [comment]
I moved my PR. Maintainer edits seems not to be allowed if the fork is made within an organisation.

**Comment by tillkruss** [comment]
@leopoiroux: Thanks!

**Comment by tillkruss** [comment]
I'll tag a new version some time this week.

**Comment by leopoiroux** [comment]
👍

**Pull request merged**
