### PR TITLE
fix support database selection with sentinel

### PR DESCRIPTION
**Pull request by bertuxdeveloper**
HI @tillkruss,
we use Redis with sentinel on our infrastructure and I notice that the DB selected is already the 0 even if we have set the WP_REDIS_DATABASE with a different value.

I see that predis library support the database choice [https://github.com/nrk/predis/issues/291# ](https://github.com/nrk/predis/issues/291# ) and I added the  `$options['parameters']['database'] = WP_REDIS_DATABASE;` in the same way of WP_REDIS_PASSWORD and it works.

Thanks in advance.
Fabio

### CODE REVIEW

**Comment by tillkruss** [comment]
Thanks @bertuxdeveloper. Could you fix the merge conflict, since this will be going into v2.0?

**Comment by bertuxdeveloper** [comment]
Hi @tillkruss,
I resolved the merge conflict.

Indicatively, when the version 2.0 is planned to be released?

Thanks a lot.

**Comment by tillkruss** [comment]
lol, not quite. Do you want me to merge it?

Screen Shot 2020-06-19 at 8 39 52 AM

The first release candidate of v2 will be live at the end of the month.

**Comment by bertuxdeveloper** [comment]
Hi @tillkruss,
sorry, my fault... I close this PR and I will open another one from develop and not from master.
Thanks a lot.

**Pull request closed without merging**
