### PR TITLE
Added ability to set ignored keys

### PR DESCRIPTION
**Pull request by therajumandapati**
This PR adds the ability to set ignored keys which will never get saved to cache. 

Based on the WordPress Support ticket [submitted here].(https://wordpress.org/support/topic/ability-to-exclude-specific-keys-from-getting-cached/#post-14141933)

### CODE REVIEW

**Comment by therajumandapati** [comment]
@tillkruss Let me know what you think.

**Comment by tillkruss** [comment]
@therajumandapati: Looks good have you tested this?

@naxvog: Any thoughts?

**Comment by tillkruss** [comment]
@therajumandapati: I'll tag a release this week. If you'd like your feature merged, please fix the conflicts.

**Comment by therajumandapati** [comment]
@tillkruss you got it, we'll fix conflicts over the next couple of days. Thank you.

**Pull request closed without merging**
